
x-data-storage-path:
  &data-storage-path
  /home/snu3/FLU_SC2_SEQUENCING

x-mira-image:
  &mira-image
  rchau88/mira:latest

services:
  mira:
    container_name: mira
    image: *mira-image
    networks:
      - mira
    privileged: true
    ports:
      - 5175:5175
    restart: always
    volumes:
      - type: bind
        source: *data-storage-path
        target: /data
    working_dir: /data

networks:
  mira:
    name: mira
