
x-data-storage-path:
  &data-storage-path
  /home/snu3/FLU_SC2_SEQUENCING

x-mira-image:
  &mira-image
  ghcr.io/cdcgov/mira-dev:v3.0.1

x-mira-backend-codebase:
  &mira-backend-codebase
  /home/snu3/Connect/MIRA/backend

x-mira-frontend-codebase:
  &mira-frontend-codebase
  /home/snu3/Connect/MIRA/frontend

services:
  mira:
    container_name: mira
    image: *mira-image
    networks:
      - mira
    privileged: true
    ports:
      - 5174:5175
    restart: always
    volumes:
      - type: bind
        source: *data-storage-path
        target: /data
      - type: bind
        source: *mira-backend-codebase
        target: /MIRA/backend
      - type: bind
        source: *mira-frontend-codebase
        target: /MIRA/frontend
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ${DOCKER_CLI_PATH:-/usr/bin/docker}
        target: /usr/local/bin/docker
        read_only: true
    working_dir: /data

networks:
  mira:
    name: mira
