version: "3.9"

x-dais-version:
  &dais-version 
  public.ecr.aws/n3z8t4o2/dais-ribosome:1.2.1

x-irma-version:
  &irma-version 
  public.ecr.aws/n3z8t4o2/irma:1.0.2p3

x-spyne-git-version:
  &spyne-git-version  
  https://github.com/CDCgov/spyne.git#prod

x-seqsender-git-version:
  &seqsender-git-version  
  https://github.com/CDCgov/seqsender.git#dev

x-mira-git-version:
  &mira-git-version  
  https://github.com/CDCgov/MIRA.git#prod

x-data-volumes:
  &data-volume
  type: bind
  source: /c/Users/snu3-su/github/mira_testdata
  target: /data

x-docker-volumes:
  &docker-socket
  type: bind
  source: /var/run/docker.sock 
  target: /var/run/docker.sock 

services:
  dais: 
    container_name: dais
    image: *dais-version
    restart: always      
    networks:
      - backend
    volumes: 
      - *data-volume
    command: tail -f /dev/null

  irma: 
    container_name: irma
    image: *irma-version
    restart: always
    networks:
      - backend
    volumes:
      - *data-volume
    command: tail -f /dev/null

  spyne: 
    container_name: spyne
    image: spyne
    restart: always
    build: 
      context: *spyne-git-version 
    depends_on:
      - dais
      - irma
    networks:
      - backend
    volumes:
      - *data-volume
      - *docker-socket
    command: tail -f /dev/null

  seqsender: 
    container_name: seqsender
    image: seqsender
    restart: always
    build: 
      context: *seqsender-git-version 
    networks:
      - backend
    volumes: 
      - *data-volume
    command: tail -f /dev/null

  mira: 
    container_name: mira
    image: mira
    restart: always
    build: 
      context: *mira-git-version  
    depends_on:
      - dais
      - irma
      - spyne
    networks:
      - frontend
      - backend
    ports: 
      - 8080:8050
    volumes:
      - *data-volume
      - *docker-socket

networks:
  backend:
    name: backend
  frontend:
    name: frontend