version: '2.6'

services:
  irma-spy-dev:
    build: 
      context: /c/users/snu3-su/irma-spy
      args:
        - BUILD_STAGE=dev
    depends_on:
      - sc2-spike-seq-dev
      - public.ecr.aws/n3z8t4o2/dais-ribosome
      - irma
    image: irma-spy-dev:v1.0.0
    networks:
      - frontend
      - backend
    container_name: irma-spy-dev
    restart: always
    ports:
      - 8080:8050
    volumes:
      - local-data:/irma-spy
      - docker-socket:/var/run/docker.sock

  irma-spy-prod:
    build: 
      context: /c/users/snu3-su/irma-spy
      args: 
        - BUILD_STAGE=prod
    depends_on:
      - sc2-spike-seq-prod
      - public.ecr.aws/n3z8t4o2/dais-ribosome
      - irma
    image: irma-spy-prod:v1.0.0
    networks:
      - frontend
      - backend
    container_name: irma-spy-prod
    restart: always
    ports:
      - 8050:8050
    volumes:
      - local-data:/data
      - docker-socket:/var/run/docker.sock

  sc2-spike-seq-dev:
    build: 
      context: /c/users/snu3-su/SC2-spike-seq
      args: 
        - BUILD_STAGE=dev
    depends_on:
      - public.ecr.aws/n3z8t4o2/dais-ribosome
      - irma
    image: isc2-spike-seq-dev:v1.0.0
    networks:
      - backend
    container_name: sc2-spike-seq-dev
    restart: always
    volumes:
      - local-data:/data
      - docker-socket:/var/run/docker.sock
      
  sc2-spike-seq-prod:
    build: 
      context: /c/users/snu3-su/SC2-spike-seq
      args: 
        - BUILD_STAGE=prod
    depends_on:
      - public.ecr.aws/n3z8t4o2/dais-ribosome
      - irma
    networks:
      - backend
    image: sc2-spike-seq-prod:v1.0.0
    container_name: sc2-spike-seq-prod
    restart: always
    volumes:
      - local-data:/data
      - docker-socket:/var/run/docker.sock

volumes:
  local-data: /c/users/snu3-su/irma-spy-test/data
  docker-socket: /var/run/docker.sock

networks:
  frontend:
  backend: