version: "3.9"

x-mira-git-version: 
  &mira-git-version 
  https://github.com/CDCgov/MIRA.git#single_mira_container

x-data-volumes:
  &data-volume
  type: bind
  source: /home/snu3/Github/FLU_SC2_SEQUENCING
  target: /data

services:
  mira: 
    container_name: mira
    image: mira:latest
    build:
      context: *mira-git-version
      args:
        - spyne_image=rchau88/spyne:latest
    restart: always
    networks:
      - frontend
    ports: 
      - 8050:8050
    volumes:
      - *data-volume

networks:
  frontend:
    name: frontend