#!/bin/bash 
# Wrapper to launch MIRA Backend API

# Define backend directory 
BACKEND_DIR=${BACKEND_DIR:-/MIRA-backend}

# Navigate to the MIRA Backend directory
cd ${BACKEND_DIR}

# Start the FastAPI app using Uvicorn
exec uvicorn app.main:app --reload --reload-dir app --host 0.0.0.0 --port 8080