
## Containerizing iSpy with Docker

There are two versions of docker images for iSpy:

- [Development version](#build-development-version-of-ispy) for continuous integration of the application
- [Production version](#build-production-version-of-ispy) for deployment of the application

## Software requirements

- Docker version >= 20.10
- Git version >= 2.21

## Container dependencies

- IRMA (stored in [AWS’s ECR](https://gallery.ecr.aws/n3z8t4o2/irma))
- Dais-Ribosome (stored in [AWS’s ECR](https://gallery.ecr.aws/n3z8t4o2/dais-ribosome))
- spyne (stored in [Quay.io's respitory](https://quay.io/repository/nbx0_cdc/spyne), also see [our Github repo ](https://github.com/nbx0/spyne) for more details about the usage of the application)

## Setting up containers

1) Pull down **IRMA**, **Dais-Ribosome**, and **spyne** docker images

IRMA version 1.0.2p3: 

```bash
docker pull public.ecr.aws/n3z8t4o2/irma:1.0.2p3
```

Dias-Ribosome version 1.2.1: 
```bash
docker pull public.ecr.aws/n3z8t4o2/dais-ribosome:1.2.1
```

spyne version 1.1.0: 
```bash
docker pull quay.io/nbx0_cdc/spyne:v1.1.0
```

(2) Run IRMA, Dais-Ribosome, and spyne containers

IRMA: 
```bash
docker run -v /path/to/data:/data --name irma -t -d public.ecr.aws/n3z8t4o2/irma:1.0.2p3
```

Dais-Ribosome:
```bash
docker run -v /path/to/data:/data --name dais-ribosome -t -d public.ecr.aws/n3z8t4o2/dais-ribosome:1.2.1
```

spyne:
```bash
docker run -v /path/to/data:/data --name spyne -t -d quay.io/nbx0_cdc/spyne:v1.1.0
```

**-v**: mount host data directory to **/data** directory inside the container <br>
**-t**: allocate a pseudo-tty <br>
**-d**: run the container in detached mode <br>

**Important Note:** make sure **/path/to/data** are the same for all containers. This directory is mounted to **/data** directory inside the container.

## Build development version of iSpy

This version allows you to mount the code base that is needed to develop the `iSpy` dashboard. Any updates or changes to the code will automatically reflects the changes inside the Docker container. This allows continuous integration (CI) of the application.

### (1) Clone this respitory

```bash
git clone https://git.biotech.cdc.gov/nbx0/iSpy.git
``` 

### (2) CD to `iSpy` folder where `Dockerfile` file is stored and build the docker image. 

__NOTE:__ `Dockerfile` contains a list of instructions and steps of how to build and deploy the `iSpy` dashboard.

- Build the docker image using a `build-arg` flag and setting `BUILD_STAGE=dev` for development stage

```bash
docker build -t iSpy-dev:v1.0.0 --build-arg BUILD_STAGE=dev .
```

or 

-  Build the docker image with a specific dockerfile for the development stage (e.g. `Dockerfile.dev`)

```bash
docker build -t iSpy-dev:v1.0.0 -f Dockerfile.dev .
```

**-t**: add a tag to an image such as the version of the application, e.g. *iSpy-dev:v1.0.0* or *iSpy-dev:latest* <br>
**`--`file, -f**: name of the Dockerfile <br>
**`--`build-arg**: set the build stage for the docker image using the `BUILD_STAGE` argument. Options are **dev** or **prod**. Default is `prod`.

__NOTE:__ _The image took approximately < 10 mins to build_

### (3) After the build is completed, you can check if the image is built successfully

```bash
docker images

REPOSITORY        TAG        IMAGE ID        CREATED        SIZE
iSpy-dev          v1.0.0     2c22887402d3    2 hours ago    1.63GB
```

### (4) To run the `iSpy-dev` container

```bash    
docker run -v /path/to/data:/data -v /path/to/iSpy:/iSpy -v /var/run/docker.sock:/var/run/docker.sock -d -p 8080:8050 --name iSpy-dev iSpy-dev:v1.0.0 
```

**NOTE:**

- Change __/path/to/data__ to your local directory where it contains all data files needed to pass to the `iSpy` dashboard. This directory is mounted to **/data** directory inside the container. Make sure **/path/to/data** are the same as other previous containers. <br>
- Change __/path/to/iSpy__ to your local `iSpy` directory. This directory must contain all of the code base needed to build the `iSpy` dashboard. <br>
- **/var/run/docker.sock:/var/run/docker.sock** is used to connect the host's docker.socket to container's docker.socket where you can run a container inside of another container. <br>

**-d**: run the container in detached mode <br>
**-v**: mount code base and data files from host directory to container directory **[host_div]:[container_dir]**. By exposing the host directory to docker container, docker will be able to access data files within that mounted directory and use it to fire up the `iSpy` dashboard.  <br>
**-p**: map the host port to the container port and then all the requests that are made to the host port will be redirected to the Docker container **[host_port]:[container_port]** <br>
**`--`name**: give an identity to the container <br>

For more information about the Docker syntax, see [Docker run reference](https://docs.docker.com/engine/reference/run/)

### (5) To check if the container is built sucessfully

```bash
docker container ps


CONTAINER ID   IMAGE               COMMAND                    CREATED        STATUS        PORTS                    NAMES
b37b6b19c4e8   iSpy-dev:v1.0.0     "bash dashboard-kickoff"   5 hours ago    Up 5 hours    0.0.0.0:8080->8050/tcp   iSpy-dev

```

**NOTE:** Here the `iSpy-dev` container is published on port **8080** on the host machine, and **8050** is the port of where the `iSpy` is published inside the container. All the requests that are made to the host port will be redirected to the Docker container.

### (6) Access the `iSpy` dashboard on the host network

You can visit the local host using your preferred web browser, type in http://localhost:8080, and check if the dashboard is indeed hosted there.

## Build production version of iSpy

This version **ONLY** allows you to mount the data files that are needed to populate the `iSpy` dashboard. In other words, you do not have access to the code base of `iSpy` but is using its latest containerized version of the code.

### (1) Clone this respitory

```bash
git clone https://git.biotech.cdc.gov/nbx0/iSpy.git
``` 

### (2) CD to `iSpy` folder where `Dockerfile` file is stored and build the docker image. 

- Since the image is built with the `prod` stage by DEFAULT, you can omit the `build-arg` flag during the build.

```bash
docker build -t iSpy-prod:v1.0.0 .
```

or 

- Build the docker image with a specific dockerfile for production stage (e.g. `Dockerfile.prod`)

```bash
docker build -t iSpy-prod:v1.0.0 -f Dockerfile.prod .
```

**-t**: add a tag to an image such as the version of the application, e.g. *iSpy-prod:v1.0.0* or *iSpy-prod:latest* <br>
**`--`file, -f**: name of the Dockerfile

__NOTE:__ _The image took approximately < 10 mins to build_

### (3) After the build is completed, you can check if the image is built successfully.

```bash
docker images

REPOSITORY        TAG        IMAGE ID        CREATED        SIZE
iSpy-prod         v1.0.0     6dab1b639b9a    2 hours ago    1.63GB
```

### (4) To run the `iSpy-prod` container

```bash   
docker run -v /path/to/data:/data -v /var/run/docker.sock:/var/run/docker.sock -d -p 8050:8050 --name iSpy-prod iSpy-prod:v1.0.0 
```

**NOTE:** 

- Change __/path/to/data__ to your local directory where it contains all data files needed to feed into the `iSpy` dashboard. This directory is mounted to ** **/data** directory inside the container. Make sure **/path/to/data** are the same as other previous containers. <br>
- **/var/run/docker.sock:/var/run/docker.sock** is used to connect the host's docker.socket to container's docker.socket where you can run a container inside of another container<br>

**-d**: run the container in detached mode <br>
**-v**: mount code base and data files from host directory to container directory **[host_div]:[container_dir]**. By exposing the host directory to docker container, docker will be able to access data files within that mounted directory and use it to feed to the `iSpy` dashboard. <br>
**-p**: map the host port to the container port and then all the requests that are made to the host port will be redirected to the Docker container **[host_port]:[container_port]** <br>
**`--`name**: give a identity to the container <br>

For more information about the Docker syntax, see [Docker run reference](https://docs.docker.com/engine/reference/run/)

### (5) To check if the container is built sucessfully

```bash
docker container ps


CONTAINER ID   IMAGE                COMMAND                    CREATED        STATUS        PORTS                    NAMES
717b0825bc66   iSpy-prod:v1.0.0     "bash dashboard-kickoff"   5 hours ago    Up 5 hours    0.0.0.0:8050->8050/tcp   iSpy-prod

```

**NOTE:** Here we are publishing the `iSpy-prod` dashboard on port **8050** on the host machine. This port is different from the **development** version which was previously launched on port **8080**.

### (6) Access the `iSpy` dashboard on the host network

You can visit the local host using your preferred web browser, type in http://localhost:8050, and check if the dashboard is indeed hosted there.

## Run genome assembly with iSpy

See [NGS Training: Running Genome Assembly with iSpy](running-ispy.html)

## Getting help

See [FAQs Guide on how to upgrade and remove older versions of iSpy](FAQs.html#how-to-upgrate-or-remove-older-versions-of-ispy-or-other-containers)
