

```{css, echo=FALSE}
thead {
  font-weight: bold;
}

thead, td {
  border: 1px solid black
}
```

# Frequently asked questions

## How do I get help?

Great question!!

MIRA is under active development. If you need help, would like to contribute, or simply want to talk about the project with like-minded individuals, we have a number of open channels for communication.

- Send us an email at [idseqsupport@cdc.gov](mailto:idseqsupport.gov)

- To report bugs or file feature requests, use the [issue tracker on Github](https://github.com/CDCgov/MIRA/issues).

- To contribute code submit a [pull request on Github](https://github.com/CDCgov/MIRA/pulls).


## How to remove containers. This is a good idea if you are having trouble with your version and need a fresh start. This will not have any effect on your sequencing data.

### iSpy uninstall

```bash
docker stop ispy
docker rm ispy
docker rmi ispy
```

### IRMA-SPY uninstall

```bash
docker stop irma-spy
docker rm irma-spy
docker rmi irma-spy
```

### MIRA uninstall

1. Open an Ubuntu terminal
2. ```bash 
    # Show running containers
    docker ps
    
    # Stop running container you want to update. In this example we are updating mira and spyne.
    docker stop mira spyne irma dais

    # Delete containers
    docker rm mira spyne irma dais

    # Delete images
    docker rmi mira spyne irma dais
    ```
3. Install the new MIRA and spyne containers: [See Docker Desktop MIRA installation](mira-dd-getting-started.html)

## How do I customize the number of cores MIRA uses?
This is best achieved by setting `resources` in the `docker-compose.yml` for a container's `deploy` settings:

For example:

```bash
spyne: 
    container_name: spyne
    image: spyne
    build: 
      context: *spyne-git-version 
    depends_on:
      - dais
      - irma
    restart: always
    networks:
      - backend
    volumes:
      - *data-volume
      - *docker-socket
    command: tail -f /dev/null
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
```
Read more [here](https://docs.docker.com/compose/compose-file/compose-file-v3/#resources) in the official Docker Docs


<br>

## Docker compose operations

<table>
<thead>
  <tr>
    <td>Command</td>
    <td>Description</td>
  </tr>
</thead>
<tbody>

  
  <tr>
    <td><a target="_blank" href="https://docs.docker.com/engine/reference/commandline/compose_build/">docker compose build</a></td>
    <td>Build or rebuild services</td>
  </tr>

  
  <tr>
    <td><a target="_blank" href="https://docs.docker.com/engine/reference/commandline/compose_config/">docker compose config</a></td>
    <td>Parse, resolve and render compose file in canonical format</td>
  </tr>

  
  <tr>
    <td><a target="_blank" href="https://docs.docker.com/engine/reference/commandline/compose_cp/">docker compose cp</a></td>
    <td>Copy files/folders between a service container and the local filesystem</td>
  </tr>

  
  <tr>
    <td><a target="_blank" href="https://docs.docker.com/engine/reference/commandline/compose_create/">docker compose create</a></td>
    <td>Creates containers for a service.</td>
  </tr>

  
  <tr>
    <td><a target="_blank" href="https://docs.docker.com/engine/reference/commandline/compose_down/">docker compose down</a></td>
    <td>Stop and remove containers, networks</td>
  </tr>

  
  <tr>
    <td><a target="_blank" href="https://docs.docker.com/engine/reference/commandline/compose_events/">docker compose events</a></td>
    <td>Receive real time events from containers.</td>
  </tr>

  
  <tr>
    <td><a target="_blank" href="https://docs.docker.com/engine/reference/commandline/compose_exec/">docker compose exec</a></td>
    <td>Execute a command in a running container.</td>
  </tr>

  
  <tr>
    <td><a target="_blank" href="https://docs.docker.com/engine/reference/commandline/compose_images/">docker compose images</a></td>
    <td>List images used by the created containers</td>
  </tr>

  
  <tr>
    <td><a target="_blank" href="https://docs.docker.com/engine/reference/commandline/compose_kill/">docker compose kill</a></td>
    <td>Force stop service containers.</td>
  </tr>

  
  <tr>
    <td><a target="_blank" href="https://docs.docker.com/engine/reference/commandline/compose_logs/">docker compose logs</a></td>
    <td>View output from containers</td>
  </tr>

  
  <tr>
    <td><a target="_blank" href="https://docs.docker.com/engine/reference/commandline/compose_ls/">docker compose ls</a></td>
    <td>List running compose projects</td>
  </tr>

  
  <tr>
    <td><a target="_blank" href="https://docs.docker.com/engine/reference/commandline/compose_pause/">docker compose pause</a></td>
    <td>Pause services</td>
  </tr>

  
  <tr>
    <td><a target="_blank" href="https://docs.docker.com/engine/reference/commandline/compose_port/">docker compose port</a></td>
    <td>Print the public port for a port binding.</td>
  </tr>

  
  <tr>
    <td><a target="_blank" href="https://docs.docker.com/engine/reference/commandline/compose_ps/">docker compose ps</a></td>
    <td>List containers</td>
  </tr>

  
  <tr>
    <td><a target="_blank" href="https://docs.docker.com/engine/reference/commandline/compose_pull/">docker compose pull</a></td>
    <td>Pull service images</td>
  </tr>

  
  <tr>
    <td><a target="_blank" href="https://docs.docker.com/engine/reference/commandline/compose_push/">docker compose push</a></td>
    <td>Push service images</td>
  </tr>

  
  <tr>
    <td><a target="_blank" href="https://docs.docker.com/engine/reference/commandline/compose_restart/">docker compose restart</a></td>
    <td>Restart service containers</td>
  </tr>

  
  <tr>
    <td><a target="_blank" href="https://docs.docker.com/engine/reference/commandline/compose_rm/">docker compose rm</a></td>
    <td>Removes stopped service containers</td>
  </tr>

  
  <tr>
    <td><a target="_blank" href="https://docs.docker.com/engine/reference/commandline/compose_run/">docker compose run</a></td>
    <td>Run a one-off command on a service.</td>
  </tr>

  
  <tr>
    <td><a target="_blank" href="https://docs.docker.com/engine/reference/commandline/compose_start/">docker compose start</a></td>
    <td>Start services</td>
  </tr>

  
  <tr>
    <td><a target="_blank" href="https://docs.docker.com/engine/reference/commandline/compose_stop/">docker compose stop</a></td>
    <td>Stop services</td>
  </tr>

  
  <tr>
    <td><a target="_blank" href="https://docs.docker.com/engine/reference/commandline/compose_top/">docker compose top</a></td>
    <td>Display the running processes</td>
  </tr>

  
  <tr>
    <td><a target="_blank" href="https://docs.docker.com/engine/reference/commandline/compose_unpause/">docker compose unpause</a></td>
    <td>Unpause services</td>
  </tr>

  
  <tr>
    <td><a target="_blank" href="https://docs.docker.com/engine/reference/commandline/compose_up/">docker compose up</a></td>
    <td>Create and start containers</td>
  </tr>

  
  <tr>
    <td><a target="_blank" href="https://docs.docker.com/engine/reference/commandline/compose_version/">docker compose version</a></td>
    <td>Show the Docker Compose version information</td>
  </tr>

</tbody>
</table>



