Assembled genomes undergo two kinds of quality control. First, at the IRMA level, reads are filtered according to length and median quality.
During the many rounds of reference editing and refinement, indels and variants must meet additional thresholds to be incorporated.
When consensus is called, base frequency, quality, and depth are considered before finalizing the sequence.

Second, consensus sequences undergo additional genome-level QC to ensure completeness and suitable confidence.

## IRMA QC 
### Nanopore QC thresholds

#### Flu
- Read length >= 150
- Insertion frequency >= 75%
- Deletion frequency >= 75%
- Minimum coverage to call base >= 50X depth
- Average base quality to call >= 10
- Mixed [IUPAC](https://www.bioinformatics.org/sms/iupac.html) base when Minor Allele Frequency >= 20%

#### Spike SARS-CoV-2
- Read length >= 125
- Insertion frequency >= 50%
- Minimum insertion coverage to call base >= 15X depth
- Deletion frequency >= 50%
- Minimum deletion coverage to call deletion >= 10X depth
- Minimum coverage to call base >= 50X depth
- Average base quality to call >= 10
- Mixed [IUPAC](https://www.bioinformatics.org/sms/iupac.html) base when Minor Allele Frequency >= 20%

#### Whole Genome SARS-CoV-2
- Read length >= 125
- Insertion frequency >= 50%
- Minimum insertion coverage to call base >= 15X depth
- Deletion frequency >= 75%
- Minimum deletion coverage to call deletion >= 10X depth
- Minimum coverage to call base >= 50X depth
- Average base quality to call >= 10
- Mixed [IUPAC](https://www.bioinformatics.org/sms/iupac.html) base when Minor Allele Frequency >= 20%

#### RSV
- Read length >= 125
- Insertion frequency >= 50%
- Minimum insertion coverage to call base >= 20X depth
- Deletion frequency >= 75%
- Minimum coverage to call base >= 20X depth
- Average base quality to call >= 10
- Mixed [IUPAC](https://www.bioinformatics.org/sms/iupac.html) base when Minor Allele Frequency >= 20%

### Illumina QC thresholds
#### Flu
- Read length >= 125 for 2x150 chemistry, >= 70 for 2x75 chemistry
- Read median quality score >= 30
- Insertion frequency >= 25%
- Deletion frequency >= 60%
- Minimum coverage to call base >= 30X depth
- Mixed [IUPAC](https://www.bioinformatics.org/sms/iupac.html) base when Minor Allele Frequency >= 20%

#### Whole Genome SARS-CoV-2
- Read length >= 80 for 2x150 chemistry, >=50 for 2x75 chemistry
- Read median quality score >= 27
- Insertion frequency >= 55%
- Minimum insertion coverage to call base >= 15X depth (30X paired)
- Deletion frequency >= 55%
- Minimum deletion coverage to call deletion >= 10X depth (30X paired)
- Minimum depth to call base >= 30X depth
- Average base quality to call >= 15
- Mixed [IUPAC](https://www.bioinformatics.org/sms/iupac.html) base when Minor Allele Frequency >= 20%

## Post-Assembly QC Curation

- Minimum median coverage of 50x for ONT, 100x for Illumina
- For SARS-CoV-2 ONT: Spike gene median coverage of 100X
- Minimum coverage of the reference length of 90%
- For SARS-CoV-2 modules: Spike gene minimum coverage length of 90%
- Less than 10 minor variants >=5% for each Flu Segment
- Less than 20 minor variants >=5% for SARS-CoV-2 whole-genome and ONT RSV
- Less than 50 variants >=5% for Illumina RSV 
- No premature stop codons in Spike (SC2), HA (Flu), NA (Flu), G (RSV), or F (RSV)

## Amino acid variant references
For influenza samples, MIRA will call amino acid variants in your sequences against the most genetically similar
candidate vaccine virus (CVV) recommended by the WHO for 
[human seasonal](https://www.who.int/publications/m/item/recommended-composition-of-influenza-virus-vaccines-for-use-in-the-2025-2026-nh-influenza-season) 
or [zoonotic viruses](https://aspr.hhs.gov/legal/Pandemic-Influenza-Strategy/Pages/Objective-1.aspx).

Current strains and their GISAID accessions are listed in the following table:

| Reference                                           | Sybtype | Accession        |
|-----------------------------------------------------|---------|------------------|
| A/Wisconsin/67/2022                                 | H1N1    | EPI_ISL_15928563 |
| A/District of Columbia/27/2023                      | H3N2    | EPI_ISL_18862356 |
| A/Anhui/1/2013                                      | H7N9    | EPI_ISL_138739   |
| A/Ann Arbor/6/1960                                  | H2N2    | EPI_ISL_130415   |
| A/Astrakhan/3212/2020_N8                            | H5N8    | EPI_ISL_1038924  |
| A/Northern Pintail/Alaska/UGAI17/4733/2017          | H6N5    | EPI_ISL_502620   |
| A/Sichuan/26221/2014                                | H5N6    | EPI_ISL_163493   |
| A/Turkey/Ontario/6118/1968                          | H8N4    | EPI_ISL_132847   |
| A/Bangladesh/0994/2011                              | H9N2    | EPI_ISL_140388   |
| A/American Wigeon/South Carolina/22-000345-001/2021 | H5N1    | EPI_ISL_17008863 |
| A/California/07/2009                                | H1N1    | EPI_ISL_31553    |
| A/Hong Kong/4801/2014                               | H3N2    | EPI_ISL_165554   |
| A/Netherlands/219/2003                              | H7N7    | EPI_ISL_67238    |
| A/Viet Nam/1203/2004                                | H5N1    | EPI_ISL_21080    |
| B/Phuket/3073/2013                                  | BYAM    | EPI_ISL_161843   |
| B/Austria/1359417/2021                              | BVIC    | EPI_ISL_983345   |
| B/Brisbane/60/2008                                  | BVIC    | EPI_ISL_115157   |
