Submission:
  NCBI:
    Username: 
    Password: 
    Spuid_Namespace: 
    BioSample_Package: Pathogen.cl.1.0
    Publication_Title: 
    Publication_Status: Unpublished
    Specified_Release_Date: 
    GenBank_Auto_Remove_Failed_Samples: false
    Link_Sample_Between_NCBI_Databases: true
    Add_Definition_Line_Accessions: true
    Submission_Position: 1
    Description:
      Organization:
        Role: 
        Type: 
        Name: 
        Address:
          Affil: 
          Div: 
          Street: 
          City: 
          Sub: 
          Postal_Code: 
          Country: 
          Email: 
          Phone: 
        Submitter:
          Email: 
          Alt_Email: 
          Name:
            First: 
            Last: 
