name: mira
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - dash-bio=0.2.0
  - dash-bootstrap-components=1.1.0
  - dash-daq=0.5.0
  - flask=1.1.2
  - flask-caching=1.10.1
  - pandas=1.0.5
  - pip=20.1.1
  - python=3.7.6
  - pip:
    - snakemake=7.16.1
    - cutadapt==4.1
    - dash==1.13.3
    - dash-core-components==1.10.1
    - dash-html-components==1.0.3
    - dash-table==4.8.1
    - flask-compress==1.5.0
    - numpy==1.19.0
    - plotly==4.8.2
    - pyyaml==6.0
